# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/raboten/c03df044-bb85-4f9c-a53f-e537b8a024a0/raceintospace-raceintospace-d9cd1cd2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/raboten/c03df044-bb85-4f9c-a53f-e537b8a024a0/raceintospace-raceintospace-d9cd1cd2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /run/media/raboten/c03df044-bb85-4f9c-a53f-e537b8a024a0/raceintospace-raceintospace-d9cd1cd2/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/raboten/c03df044-bb85-4f9c-a53f-e537b8a024a0/raceintospace-raceintospace-d9cd1cd2/CMakeFiles /run/media/raboten/c03df044-bb85-4f9c-a53f-e537b8a024a0/raceintospace-raceintospace-d9cd1cd2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/raboten/c03df044-bb85-4f9c-a53f-e537b8a024a0/raceintospace-raceintospace-d9cd1cd2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named libs

# Build rule for target.
libs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs
.PHONY : libs

# fast build rule for target.
libs/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/libs.dir/build.make lib/CMakeFiles/libs.dir/build
.PHONY : libs/fast

#=============================================================================
# Target rules for targets named ext_libogg

# Build rule for target.
ext_libogg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_libogg
.PHONY : ext_libogg

# fast build rule for target.
ext_libogg/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/ext_libogg.dir/build.make lib/CMakeFiles/ext_libogg.dir/build
.PHONY : ext_libogg/fast

#=============================================================================
# Target rules for targets named ext_jsoncpp

# Build rule for target.
ext_jsoncpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_jsoncpp
.PHONY : ext_jsoncpp

# fast build rule for target.
ext_jsoncpp/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/ext_jsoncpp.dir/build.make lib/CMakeFiles/ext_jsoncpp.dir/build
.PHONY : ext_jsoncpp/fast

#=============================================================================
# Target rules for targets named ext_physfs

# Build rule for target.
ext_physfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_physfs
.PHONY : ext_physfs

# fast build rule for target.
ext_physfs/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/ext_physfs.dir/build.make lib/CMakeFiles/ext_physfs.dir/build
.PHONY : ext_physfs/fast

#=============================================================================
# Target rules for targets named ext_libtheora

# Build rule for target.
ext_libtheora: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_libtheora
.PHONY : ext_libtheora

# fast build rule for target.
ext_libtheora/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/ext_libtheora.dir/build.make lib/CMakeFiles/ext_libtheora.dir/build
.PHONY : ext_libtheora/fast

#=============================================================================
# Target rules for targets named ext_libvorbis

# Build rule for target.
ext_libvorbis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ext_libvorbis
.PHONY : ext_libvorbis

# fast build rule for target.
ext_libvorbis/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/ext_libvorbis.dir/build.make lib/CMakeFiles/ext_libvorbis.dir/build
.PHONY : ext_libvorbis/fast

#=============================================================================
# Target rules for targets named raceintospace_display

# Build rule for target.
raceintospace_display: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raceintospace_display
.PHONY : raceintospace_display

# fast build rule for target.
raceintospace_display/fast:
	$(MAKE) $(MAKESILENT) -f src/display/CMakeFiles/raceintospace_display.dir/build.make src/display/CMakeFiles/raceintospace_display.dir/build
.PHONY : raceintospace_display/fast

#=============================================================================
# Target rules for targets named raceintospace_protobuf

# Build rule for target.
raceintospace_protobuf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raceintospace_protobuf
.PHONY : raceintospace_protobuf

# fast build rule for target.
raceintospace_protobuf/fast:
	$(MAKE) $(MAKESILENT) -f src/protobuf/CMakeFiles/raceintospace_protobuf.dir/build.make src/protobuf/CMakeFiles/raceintospace_protobuf.dir/build
.PHONY : raceintospace_protobuf/fast

#=============================================================================
# Target rules for targets named game_test

# Build rule for target.
game_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_test
.PHONY : game_test

# fast build rule for target.
game_test/fast:
	$(MAKE) $(MAKESILENT) -f src/game/CMakeFiles/game_test.dir/build.make src/game/CMakeFiles/game_test.dir/build
.PHONY : game_test/fast

#=============================================================================
# Target rules for targets named raceintospace

# Build rule for target.
raceintospace: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raceintospace
.PHONY : raceintospace

# fast build rule for target.
raceintospace/fast:
	$(MAKE) $(MAKESILENT) -f src/game/CMakeFiles/raceintospace.dir/build.make src/game/CMakeFiles/raceintospace.dir/build
.PHONY : raceintospace/fast

#=============================================================================
# Target rules for targets named news2png

# Build rule for target.
news2png: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 news2png
.PHONY : news2png

# fast build rule for target.
news2png/fast:
	$(MAKE) $(MAKESILENT) -f src/utils/CMakeFiles/news2png.dir/build.make src/utils/CMakeFiles/news2png.dir/build
.PHONY : news2png/fast

#=============================================================================
# Target rules for targets named data_decoder

# Build rule for target.
data_decoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_decoder
.PHONY : data_decoder

# fast build rule for target.
data_decoder/fast:
	$(MAKE) $(MAKESILENT) -f src/utils/CMakeFiles/data_decoder.dir/build.make src/utils/CMakeFiles/data_decoder.dir/build
.PHONY : data_decoder/fast

#=============================================================================
# Target rules for targets named but2png

# Build rule for target.
but2png: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 but2png
.PHONY : but2png

# fast build rule for target.
but2png/fast:
	$(MAKE) $(MAKESILENT) -f src/utils/CMakeFiles/but2png.dir/build.make src/utils/CMakeFiles/but2png.dir/build
.PHONY : but2png/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... dist"
	@echo "... ext_jsoncpp"
	@echo "... ext_libogg"
	@echo "... ext_libtheora"
	@echo "... ext_libvorbis"
	@echo "... ext_physfs"
	@echo "... libs"
	@echo "... run"
	@echo "... but2png"
	@echo "... data_decoder"
	@echo "... game_test"
	@echo "... news2png"
	@echo "... raceintospace"
	@echo "... raceintospace_display"
	@echo "... raceintospace_protobuf"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

